#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Uruchomienie komend w kontenerze e-commerce-store
docker compose exec -T e-commerce-store sh -c "cd /app && npm run format && npm run prettier && npm run lint && npm run test"
