#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Przejdź do katalogu głównego repo (tam, gdzie docker-compose.yml)
cd "$(git rev-parse --show-toplevel)" || exit 1

# Upewnij się, że kontener jest uruchomiony
docker compose up -d e-commerce-store

# Wykonaj komendy w kontenerze
docker compose exec -T e-commerce-store sh -c "cd /app && npm run format && npm run prettier && npm run lint && npm run test"
